FROM node:19.5.0-alpine as build

RUN apk add --no-cache bash git make gcc g++ python3
WORKDIR /usr/app
COPY simple-backend /usr/app
RUN git clone https://github.com/vishnubob/wait-for-it.git
RUN npm install && \
    npm rebuild bcrypt --build-from-source && \
    apk del make gcc g++ python3

EXPOSE 4000
