FROM node:16-alpine as build

WORKDIR /usr/local/app
RUN npm install -g @angular/cli
COPY simple-frontend /usr/local/app

RUN npm install
RUN ng build

FROM nginx:latest as runtime
COPY --from=build /usr/local/app/dist/simple-frontend /usr/share/nginx/html